/**
 * Content Configuration — Single source of truth for all portfolio categories
 *
 * Each category maps to an array of thumbnail objects:
 *   - src: key into the thumbnailModules map (relative path from assets/thumbnails/)
 *   - alt: accessible description
 *   - cols: how many grid columns this item spans (1–4)
 *   - rows: how many grid rows this item spans (1–4)
 *   - title: (optional) display name shown in detail view
 *   - description: (optional) text shown below image in detail view
 *   - detailLayout: (optional) override auto AR-based layout in detail view
 *       'info-left'  — image right, info panel left
 *       'info-right' — image left, info panel right
 *       'info-below' — image top, info panel below
 *       omit for auto (determined by aspect ratio)
 *
 * cols/rows create the irregular mosaic — some items are 2x2, 1x2, 2x1, etc.
 * CSS Grid's `grid-auto-flow: dense` packs them tightly to fill gaps.
 */

/**
 * import.meta.glob — Vite's way of importing many files at once.
 *
 * At build time, Vite scans the glob pattern and generates an object like:
 *   { './3d-art/0169.png': '/assets/0169-abc123.png', ... }
 *
 * The `eager: true` option means all imports resolve immediately (no async).
 * The `as: 'url'` option returns just the resolved URL string (not the module).
 *
 * This is how we avoid the "dynamic string path" trap — every image goes through
 * Vite's asset pipeline and gets hashed URLs that work in production.
 *
 * Think of it like Unity's Resources.LoadAll<Texture2D>("thumbnails/") —
 * it pre-discovers all matching assets at compile time.
 */
const thumbnailModules = import.meta.glob(
  '../assets/thumbnails/**/*.{jpg,jpeg,png,webp,avif,mp4,webm}',
  { eager: true, import: 'default' }
);

/**
 * Splat asset glob — same pattern as thumbnails but for .spz files.
 *
 * `as: 'url'` tells Vite "give me the resolved URL, don't import the file contents."
 * At build time this becomes a map like:
 *   { '../assets/splats/crystal.spz': '/assets/crystal-abc123.spz' }
 *
 * The .spz file itself is NOT downloaded at page load — it's just a URL string.
 * The actual fetch happens when SplatViewer mounts and requests it.
 */
const splatModules = import.meta.glob(
  '../assets/splats/**/*.spz',
  { eager: true, query: '?url', import: 'default' }
);

/**
 * Resolves a splat filename (like 'crystal.spz') to a Vite-processed URL.
 * Parallel to resolveThumbnail() — same glob-based pattern.
 */
export function resolveSplat(filename) {
  const key = `../assets/splats/${filename}`;
  const resolved = splatModules[key];
  if (!resolved) {
    console.warn(`Splat not found: ${filename}`);
    return '';
  }
  return resolved;
}

/**
 * Resolves a relative thumbnail path (like '3d-art/0169.png') to a Vite-processed URL.
 * Returns the hashed URL for production or the dev server URL in development.
 */
export function resolveThumbnail(relativePath) {
  // The glob keys are relative to THIS file, so they start with '../assets/thumbnails/'
  const key = `../assets/thumbnails/${relativePath}`;
  const resolved = thumbnailModules[key];
  if (!resolved) {
    console.warn(`Thumbnail not found: ${relativePath}`);
    return '';
  }
  return resolved;
}

// Extensions, grouped by media kind. `image` fallback uses the originally
// referenced extension (png/jpg/jpeg) — preserves author intent from content.js.
const IMAGE_EXTS = new Set(['png', 'jpg', 'jpeg']);
const VIDEO_EXTS = new Set(['mp4', 'webm', 'mov', 'm4v']);
const MIME_BY_EXT = {
  avif: 'image/avif',
  webp: 'image/webp',
  webm: 'video/webm',
  mp4: 'video/mp4',
};

// Pixel dimensions for every thumbnail, generated by scripts/optimize-assets.sh.
// Maps 'relative/path.ext' → [width, height]. Two consumers:
//   - width/height attributes on <img>/<video> so the browser reserves layout
//     space before decode (prevents layout shift)
//   - the `w` descriptor of the full-size srcset candidate (tier widths are
//     known by construction: 480/960)
import ASSET_DIMS from './asset-dims.json';

// Responsive tier widths emitted by the optimizer as -{W}w.{webp,avif}
// siblings. Must match TIER_WIDTHS in scripts/optimize-assets.sh.
const TIER_WIDTHS = [480, 960];

function tryResolve(basePath, ext) {
  const key = `../assets/thumbnails/${basePath}.${ext}`;
  return thumbnailModules[key] || null;
}

/**
 * Looks up [width, height] for a thumbnail path. Falls back to sibling
 * extensions when the exact file isn't in the manifest — e.g. content.js may
 * reference foo.webm while the optimizer deleted it in favour of foo.mp4
 * (inversion guard), and all variants of one image share dimensions anyway.
 */
export function dimsFor(relativePath) {
  let d = ASSET_DIMS[relativePath];
  if (!d) {
    const dot = relativePath.lastIndexOf('.');
    if (dot > 0) {
      const base = relativePath.slice(0, dot);
      for (const ext of ['png', 'jpg', 'jpeg', 'mp4', 'webm', 'webp', 'avif']) {
        d = ASSET_DIMS[`${base}.${ext}`];
        if (d) break;
      }
    }
  }
  return d ? { width: d[0], height: d[1] } : null;
}

/**
 * Returns all available variants for a thumbnail path, in preference order.
 *
 * For images, `sources` holds the modern formats the browser should try first
 * (avif, webp), each as a srcset string. When the optimizer emitted width
 * tiers (foo-480w.webp ...) the srcset carries `w` descriptors so the browser
 * can pick the smallest candidate that covers the slot (see `sizes` in
 * createMediaElement) — think mipmaps: same image, multiple resolutions,
 * picked by on-screen size. `fallback` is the originally referenced file
 * (png/jpg/jpeg) — every browser can decode it, so it's the `<img>` inside
 * `<picture>`.
 *
 * For videos, `sources` holds webm (preferred) then mp4 (universal fallback).
 *
 * Returns null if the path is unknown, so callers can mirror existing
 * `if (url)` guards with `if (element)`.
 */
export function variantsFor(relativePath) {
  const dot = relativePath.lastIndexOf('.');
  if (dot < 0) return null;
  const basePath = relativePath.slice(0, dot);
  const ext = relativePath.slice(dot + 1).toLowerCase();
  const dims = dimsFor(relativePath);

  if (IMAGE_EXTS.has(ext)) {
    const fallbackUrl = tryResolve(basePath, ext);
    if (!fallbackUrl) {
      console.warn(`Thumbnail not found: ${relativePath}`);
      return null;
    }
    const sources = [];
    for (const modern of ['avif', 'webp']) {
      const full = tryResolve(basePath, modern);
      if (!full) continue;
      const candidates = [];
      for (const w of TIER_WIDTHS) {
        const tierUrl = tryResolve(`${basePath}-${w}w`, modern);
        if (tierUrl) candidates.push(`${tierUrl} ${w}w`);
      }
      // `w` descriptors must be all-or-nothing within one srcset, and the
      // full-size candidate needs its real width from the manifest. Missing
      // either → degrade to the single-URL srcset (today's behavior).
      if (candidates.length > 0 && dims) {
        candidates.push(`${full} ${dims.width}w`);
        sources.push({ type: MIME_BY_EXT[modern], srcset: candidates.join(', ') });
      } else {
        sources.push({ type: MIME_BY_EXT[modern], srcset: full });
      }
    }
    return { kind: 'image', sources, fallback: { url: fallbackUrl, ext }, dims };
  }

  if (VIDEO_EXTS.has(ext)) {
    const sources = [];
    // Preferred first: webm (smaller), then mp4 (universal).
    for (const vext of ['webm', 'mp4']) {
      const url = tryResolve(basePath, vext);
      if (url) sources.push({ type: MIME_BY_EXT[vext], url });
    }
    if (sources.length === 0) {
      console.warn(`Thumbnail not found: ${relativePath}`);
      return null;
    }
    return { kind: 'video', sources, dims };
  }

  console.warn(`Unsupported thumbnail extension: ${relativePath}`);
  return null;
}

/**
 * General section content — text-based "CV" instead of a thumbnail mosaic.
 * Structured as data so the rendering logic stays in main.js.
 */
export const GENERAL_CONTENT = {
  name: 'Tomás Correa',
  title: 'Technical Artist',
  subtitle: 'Game Developer · Creative Engineer',
  summary:
    'I solve visual problems at the boundary between art and code, ' +
    "building shaders, VFX, tools, and pipelines that make artists' " +
    'lives easier and games look and feel better. I develop systems for gameplay and player-machine interfaces, ' +
    "and I'm increasingly asking what those systems do beyond the " +
    'screen: how games shape collective memory, social identities, and civic life.',
  // 'I solve visual problems at the boundary between art and code. ' +
  // 'I build shaders, VFX, tools, and pipelines that help artists work faster ' +
  // 'and games look better — always thinking in systems, always grounded in ' +
  // "real production needs, and always focused on the player's experience.",
  skills: [
    { label: 'Shaders & VFX', detail: 'Real-time shaders, particle systems, post-processing' },
    {
      label: '3D Art & Materials', detail: 'Modelling, texturing, procedural workflows in Blender',
    },
    { label: 'Tools & Pipelines', detail: 'Custom editor tools, asset pipelines, workflow automation' },
    { label: 'Game Development', detail: 'ARBO: Arena Tactics (shipped on Steam): Technical Artist & lead developer' },
  ],
  tools: ['Unity', 'Blender', 'C#', 'Python', 'HLSL/GLSL', 'SQL'],
  contacts: [
    { platform: 'linkedin', url: 'https://www.linkedin.com/in/tomás-correa-551b0a243', label: 'LinkedIn' },
    { platform: 'github', url: 'https://github.com/tomascorreag', label: 'GitHub' },
    { platform: 'discord', copyText: 'eltomoco', label: 'Discord' },
    // Split at build time so a naive HTML/source scraper sees two unrelated
    // strings instead of a literal `user@domain`. Stops casual crawlers only;
    // a real harvester can still join the halves. Plus-addressing (+3)
    // doubles as a disposable tag we can retire if spam gets bad.
    { platform: 'email', copyText: ['tomcorrea3+3', 'gmail.com'].join('@'), label: 'Email' },
  ],
  cta: 'Scroll the other sections to see the work.',
};

/**
 * Games section — each entry is a game or interactive artifact with a banner, description, and links.
 *   - src: thumbnail path (relative to assets/thumbnails/) — should be 2:1 aspect ratio
 *   - title: game name
 *   - description: short blurb
 *   - links: array of { label, url } shown as buttons below the description
 *   - page: (optional) markdown string for an article page (parsed by utils/markdown.js)
 *
 * Supported markdown syntax:
 *   ## Heading          → <h3> section heading
 *   Paragraph text      → <p> (blank-line separated)
 *   ---                 → <hr> divider
 *   ![alt](src)         → <figure> image/video via createMediaElement
 *   *caption*           → <figcaption> (line after image only)
 *   [Label|icon](url)   → link button (consecutive lines group)
 */
export const GAMES = [
  {
    id: 'arbo',
    src: 'Games/ARBO/ARBO_thumb.jpg',
    title: 'ARBO: Arena Tactics',
    description: 'ARBO: Arena Tactics is a two-player tactically deep strategy video game, shipped on Steam in closed alpha, where I was the Technical Artist and co-lead developer.',
    links: [
      { label: 'Steam', icon: 'steam', url: 'https://store.steampowered.com/app/2914810/ARBO_Arena_Tactics/' },
      { label: 'Website', icon: 'website', url: 'https://arbo.xyz/' },
    ],
    page: `
## About the Project

In the near future, an alien species known as the **ARBO** arrives on Earth as humanity's guardians: they have come, they say, to warn us of the **Abyssals**, another alien race intent on enslaving the world. Racing to build an army of automata to defend itself, humanity instead gives rise to a wholly new form of artificial life: the **Syhm**. Then the ARBO's true intentions surface, and war breaks out between four factions: humans, Syhm, Abyssals, and ARBO.

Two players each command a small team of heroes and face off on a grid-based battlefield. Before every match you build your own deck of cards, so each game blends careful tactics with strategic deck-building. The goal is simple: outthink your opponent, control the ground, and knock out their team.

- **Four hero classes**, each with a distinct way of playing
- **Cards you unlock and collect**, then build into your own decks, with dynamic and varied card mechanics where the card energy pool doubles as health, so every action is a trade-off between attacking and staying alive
- **Dynamic battlefields with water, ice, lava, and high and low ground** that change how you move and what you can reach
- **Four ways to play**, including online matches (casual and ranked), single-player boss fights, and an experimental mode where you command your team by typing plain-language orders to an AI

---

## My Role

I entered the project as a 3D artist working on the game art. Eventually I moved into development and became the Technical Artist and one of two core developers at **ReBlink**, the Canadian studio where ARBO was built, across five years on a small multidisciplinary team (2021-2026). I was responsible for:

- **The real-time visual pipeline**: the system that turns the game's art into what you see on screen, frame by frame
- **Liaison** between engineering, Art, and Game Design departments.
- **All visual effects**: explosions, impacts, energy, and everything that moves and glows in combat
- The **entire game logic, interface and overall feel of using the game** (co-developed)
- The **multiplayer game backend**, infrastructure to support online multiplayer games (co-developed)
- **Custom tools inside Unity** that let the rest of the team build and tune content without writing code

---

## Why I Joined

I joined ReBlink early and stayed for five years because the project offered something rare: complete ownership of a commercial game's visual identity, end to end. Every character, effect, and arena (how it looked, how it moved, how it felt to play) passed through my hands, and I built the core systems of the game, spanning from backend to UX. That work sits exactly on the line between art and engineering, which is where I do my best work. Shipping it on Steam, with a small team, after four years of building it together, is the professional achievement I'm proudest of.

---

![ARBO Molecular Punch VFX](Games/ARBO/punch.jpg)
*Molecular Punch on the Abyssal Pit map. Custom VFX, shader, and post-processing work.*

---

## Technical Highlights

- A custom real-time **shader pipeline** in Unity's URP, combining Shader Graph with hand-written HLSL/GLSL
- **VFX** spanning particle systems, VFX Graph, and fully custom effects in C#
- **Editor tooling** that lets designers author and tune content without writing code
- **Fully data-driven content**: classes, protocols, operations, and arena setups defined in JSON profiles, so balance and content iteration never touches engine code
- **Deep C# combat logic**: a hex-tile based map system with pathfinding and line-of-sight, a deep status-effect system that affected everything from movement to chance-to-hit, and many other complex systems.
- **Two-tier networking**: Photon Fusion and Colyseus for matchmaking, game lobbies, and in-game multiplayer
- **Server-driven AI opponents**: an LLM-based AI opponent with a reasoning agent powering the Prompt-Battler mode

![ARBO Incendiary Flames VFX](Games/ARBO/flamethrower.jpg)
*Incendiary Flames. Particle systems and post-processing on display.*

[Steam|steam](https://store.steampowered.com/app/2914810/ARBO_Arena_Tactics/)
[Website|website](https://arbo.xyz/)
`,
  },
  {
    id: 'paramo',
    type: 'spritesheet',
    spritesheet: {
      file: 'Games/Paramo/MainTitle_animated.png',
      frames: 24, first: 16, count: 8, fps: 10,
      // Pixel-perfect: native frame is 256×64; render at integer 1× = 256×64.
      frameWidth: 256, frameHeight: 64, scale: 1,
      frameAspect: '4 / 1',
      background: '#94a8bf',
    },
    title: 'Páramo',
    description: 'Páramo is a WIP environmental strategy game I\'m designing and developing entirely on my own, set on a threatened ecosystem in the Andes.',
    links: [
      { label: 'Play', icon: 'website', url: 'https://tomascorreag.github.io/Paramo/' },
    ],
    page: `
## About the Project

A mix of sandbox and environmental strategy, built in Godot 4. You play a field coordinator protecting a Colombian páramo, a high mountain ecosystem that acts as a water factory for millions of beings downstream. A glacial lake sits at the summit. If it dies, everything below it dies with it.

Threats climb the mountain from below:

- **Extractive:** illegal miners, licensed mining operations, and land speculators
- **Biological:** invasive grasses creeping uphill and stray cattle trampling the soil
- **Human:** careless tourists, campers who start fires, and subsistence farmers with no other options
- **Environmental:** drought, wildfire, erosion, and a steadily worsening climate you can never beat

Three things keep a run going. **Water** comes from the ecosystem itself, **funding** from grants and eco-tourism, and **community support** decides whether the people who live nearby are your allies or your adversaries.

![Páramo isometric tile system](Games/Paramo/Large.png)
*Isometric tile grid with elevation, vegetation, and terrain variety.*

---

## My Role

Solo project (2026-present). The design, the code, the pixel art, and the writing are all mine, built in Godot 4 with isometric pixel art.

---

## Why I Made It

I wanted to make an argument through play rather than through a script, a game whose *rules* make the case, not its dialogue. The idea (game designers call it procedural rhetoric) is that if you strip away all the words and the way the game plays still convinces you of something, then the argument is built into the system itself.

The core claim I'm building toward: conservation is uneven, depends on the people who live there, and is partly a fight you can't fully win. No amount of skill turns you into a savior.

The rules carry the smaller arguments:

- **Destruction is cheap; repair is expensive.** A frailejón plant takes years to grow and seconds to burn, and scarred land never fully recovers.
- **Harm is delayed.** Contamination of the mountain lake stays invisible until it's nearly irreversible, so you have to act before the damage shows.
- **Walling the mountain off doesn't work.** Locking people out instead of working with them destroys your support and multiplies the threats.
- **The legal threats are as bad, or worse, as the illegal ones.** Licensed mining can't be physically stopped, and even the legal route to fight it can lose.
- **Climate is a ceiling, not an enemy.** There's no way to beat it, only to adapt.
- **The land remembers.** Damage is partly permanent, and the end screen shows you what was lost, not a score.

![Páramo mountain at dusk](Games/Paramo/Small.png)
*The mountain at dusk: stream, vegetation gradients, and atmospheric fog.*

---

## Technical Overview

Godot 4, isometric pixel art. Every system is data-driven, so new content is configuration rather than code.

- **Tile-based ecosystem simulation:** per-tile health states, moisture propagation, and altitude-dependent rules
- **Threat spawner:** seasonal intensity curves, weighted randomness, and climate escalation
- **Fog-of-war and visibility:** monitoring stations, ranger patrols, and directional audio cues
- **Two interaction tiers:** field presence (planting, firefighting) and station management (legal action, hiring, strategy)

*Work in progress (2026-present), targeting a vertical-slice release: procedural levels with a different mountain every playthrough, the core threat and tool sets, and the full resource loop.*

---

[Play|website](https://tomascorreag.github.io/Paramo/)
`,
  },
  {
    id: 'scars-of-violence',
    src: 'artifacts/MapColombia_thumb.png',
    // kindLabel: deck-card corner chip. Without it this entry (it lives in
    // GAMES) would read "GAME" — wrong register for a memory artifact.
    kindLabel: 'ARTIFACT',
    title: 'Scars of Violence',
    description: 'Scars of Violence is an interactive map of Colombia that I designed, built, and sourced all the data for, charting seventy years of the country\'s armed conflict.',
    links: [
      { label: 'Explore', icon: 'website', url: 'https://tomascorreag.github.io/MapColombia/?lang=en' },
    ],
    page: `
## About the Project

An interactive, browser-based map of Colombia that shows the documented violence of the country\'s armed conflict (1958-present) as **wounds on the land that heal into permanent scars**. Every mark is drawn from the case-by-case record compiled by Colombia's **Centro Nacional de Memoria Histórica** (CNMH), the national body tasked with documenting the conflict.

Time is the central dimension. As the timeline plays from 1958 to the present:

- Each documented event appears on its exact date, as a wound at the place it happened. Its size reflects the number of victims.
- The wound glows while fresh, then fades over roughly three years, leaving a **permanent scar** that never disappears. By the end the map is not empty, it is covered in seven decades of accumulated marks.
- Blood-like tendrils spread from each wound across the surrounding land, denser where there were more victims, settling into thin, dark, permanent traces.
- Clicking a wound or scar opens the record behind it: what happened, when, where, and who the victims were, with its source citation.

The wound-and-scar metaphor is the heart of the piece: violence is an injury to a territory and its people, not a series of isolated incidents, and its marks persist. A massacre in 1997 is still visible in 2026, because it still persists in the people's collective and individual memory.

---

## My Role

Solo project (2026). The concept, the design, the code, and all the data processing are mine. The underlying records come from the CNMH's published archive; turning that archive into a living, navigable map is my work.

---

## Why I Made It

**Rutas del Conflicto** (rutasdelconflicto.com) is the direct inspiration. Their navigable, place-by-place archive of the conflict's massacres showed me that memory work could take the form of a map rather than a linear narrative. This piece keeps their core gesture (geography as the way into the conflict) while experimenting with a more visceral visual register: animation, accumulation, the wound-and-scar metaphor, to test whether the territory's marking can be *felt* as well as consulted. It is an homage and an experiment on top of their idea, not a correction of it.

Something Rutas does especially well is the rigorous verification and narrative breakdown behind each event: a documented account of what happened, to whom, and how. That detail is what humanises the record and gives it emotional weight, more than any coordinate or victim count can. I couldn't find reliable breakdowns like that for most of the acts shown here, so for now most marks carry only their structured record. I'm writing those narratives in for some of the events, and raising that narrative impact little by little.

The conflict's toll is usually communicated as aggregate numbers, and aggregates anaesthetise. The hypothesis is that a spatial-temporal rendering can do what a table cannot: convey that the violence had a *shape*: that it concentrated in specific regions, moved across the country in waves, and left wounds that are both spatial and temporal, and still visible decades later.

The second motivation is the **CNMH** itself. Its patient, rigorous, case-by-case documentation of the conflict in SIEVCAC is one of the most important memory undertakings in the country, and it deserves to be seen by more than researchers who can parse a CSV. This project puts interactive data visualisation at the service of an archive that already exists, rather than making a new claim about the conflict.

---

## Commitments

Because the archive records real victims, the design carries non-negotiable constraints:

- **Fidelity over drama.** Every mark corresponds to a documented case with a citation back to its source record. Missing values stay missing and are disclosed; the emotional force must come from the truth of the data, not embellishment of it. No coordinate, date, or victim count is ever estimated, interpolated, or fabricated.
- **Interpretation is labeled.** The wound metaphor is an authored reading, and the interface says so. The viewer can always reach the underlying record.
- **Dignity.** The archive is published for memory, research, and education. The aesthetic aims for gravity, a dark cartographic register, not spectacle.

---

[Explore the Map|website](https://tomascorreag.github.io/MapColombia/?lang=en)
`,
  },
  {
    id: 'matrix',
    type: 'spritesheet',
    spritesheet: {
      file: 'Games/Matrix/Neo_run_spriteSheet.png',
      frames: 8, first: 0, count: 8, fps: 10,
      // Pixel-perfect: native frame is 64×64; render at integer 2× = 128×128.
      frameWidth: 64, frameHeight: 64, scale: 2,
      frameAspect: '1 / 1',
      background: 'transparent',
    },
    title: 'The Matrix',
    description: 'The Matrix is a short, playable 2D platformer demo I built on my own in Unity, styled after the look of an old CRT television.',
    links: [
      { label: 'Play', icon: 'website', url: 'https://tomascorreag.github.io/the-matrix-vertical-slice/' },
    ],
    page: `
## About the Project

A short, playable slice of a 2D platformer set in the world of *The Matrix*: you run and jump as Neo through a side-scrolling level, the whole screen dressed in the glow and scanlines of an old CRT television.

Built as an exercise in pixel art and post-processing effects.

---

## My Role

Built on my own in **Unity**:

- A custom **CRT screen shader** that gives the whole game the look of an old television: scanlines, glow, and curved glass
- **Pixel-art character animation**, driven by hand-made sprite sheets in Aseprite.
- The platformer movement and the level itself

---

## Why I Made It

A focused study in two things I wanted to get right: a convincing CRT screen effect and crisp pixel-art movement, wrapped in something small and actually playable rather than a still image.

---

[Play|website](https://tomascorreag.github.io/the-matrix-vertical-slice/)
`,
  },
];

export const CATEGORIES = {
  'General': [
    // Empty until you add images to src/assets/thumbnails/general/
  ],
  '3D Tech': [
    // Splat items use type: 'splat' to trigger the 3D viewer in detail view.
    // The thumbnail shows a static render; clicking opens the interactive viewer.
    // splat.file → filename in src/assets/splats/, resolved via resolveSplat().
    // splat.camera → optional [x,y,z] camera position override for this piece.

    // Add entries here as you export splats from Blender:
    // { src: '3d-assets/crystal.png', alt: 'Crystal material', cols: 2, rows: 2,
    //   title: 'Crystal', description: '...', type: 'splat',
    //   splat: { file: 'crystal.spz' } },
    {
      id: 'flesh', src: '3d-assets/fleshThumb.png', alt: 'Procedural raw flesh material', cols: 4, rows: 2,
      title: 'Procedural Raw Flesh Material',
      description: 'A raw-flesh material I built and sell for Blender, realistic living tissue with full control over its look.',
      page: `
## About

![Raw flesh material: wet, fresh tissue](3d-assets/flesh_details/var1_comp.png){right}

Realistic raw, living tissue with fine control over colour, wetness, and surface detail. Surface wetness, colour, and subsurface depth are all art-directable. It is one of my commercial materials and a consistent best-seller, with over 1,000 sales on Superhive (Blender Market). A portion of the proceeds from all my products goes to the Blender Foundation Development Fund, supporting the software they are built with.

[Buy on Superhive|website](https://superhivemarket.com/creators/tomoco)

---

## My Role

Designed and built entirely by me in **Blender (Cycles)**. I also package and sell it.

---

## Why I Made It

I built it as a product: a fully parametric organic-tissue material other artists can buy and reuse. I also use it in my own work, for example it can be seen in *Ardo*, in the **3D Art** section.

![Flesh material variation](3d-assets/flesh_details/var2_comp.png)
![Flesh material variation](3d-assets/flesh_details/var3_comp.png)

![Flesh material variation](3d-assets/flesh_details/var4_comp.png)
![Flesh material variation](3d-assets/flesh_details/var5_comp.png)
`,
    },
    {
      id: 'ice', src: '3d-assets/iceThumb.png', alt: 'Procedural ice in a glass', cols: 4, rows: 2,
      title: 'Procedural Ice',
      description: 'A reusable Blender setup I built for creating almost any kind of ice, shown here as cubes in a glass with a drink.',
      page: `
## About

![The full range of ice the setup can produce](3d-assets/ice_details/AllVars.png){right}
*One setup, many possible variations*

One setup that can produce a wide range of ice: different shapes, clarity, and surface looks. The version shown here, classic ice in a glass with a drink, is just one of many.

It is one of my commercial products, available on Superhive (Blender Market). A portion of the proceeds from all my products goes to the Blender Foundation Development Fund, supporting the software they are built with.

[Buy on Superhive|website](https://superhivemarket.com/creators/tomoco)

---

## My Role

Built entirely by me in **Blender**, combining geometry generation (Geometry Nodes), surface/volume shading, and the way light scatters inside the ice (volumetric shading).

![Glass variation](3d-assets/ice_details/Glass_Var2.png)
![Glass variation](3d-assets/ice_details/Glass_Var3.png)

---

## Why I Made It

I built it for my own personal and commercial projects: a flexible, reusable tool for ice of any shape or clarity, rather than something rebuilt from scratch each time. Once it was general enough to reuse across my own work, it also became one of the products I sell.
`,
    },
    {
      id: 'toon', src: '3d-assets/toonThumb.webm', alt: 'Stylised toon shader render', cols: 4, rows: 2,
      title: 'Stylised Toon Shader',
      description: 'A Blender shader I built that makes 3D models look hand-illustrated rather than photo-real, using the style of Moebius as a reference.',
      page: `
## About

Applied to a 3D model, the shader replaces realistic shading with flat bands of light and clean outlines, so renders read as drawings rather than photographs, pushed toward an illustrated, Moebius-like look.

![A head turntable showing the toon shader in motion](3d-assets/toon_details/toonHead.mp4)
*Flat light bands and clean outlines hold up under animation*

---

## My Role

Built entirely by me in **Blender (EEVEE)**, a non-photorealistic shader using ramp shading and line work.

---

## Why I Made It

A study in non-photorealistic rendering: getting 3D to read as a drawing, and learning the techniques behind a stylised, illustrated look I admire.
`,
    },
    {
      id: 'eyes', src: '3d-assets/eyeThumb.png', alt: 'Procedural rigged eye', cols: 2, rows: 2,
      title: 'Procedural Eyes',
      description: 'A detailed, anatomically accurate eye I built in Blender, generated procedurally, fully adjustable, and rigged to animate.',
      page: `
## About

![A procedural eye: iris pattern and sclera veining](3d-assets/eye_details/var2.png){right}

Every part of the eye's look (the iris pattern, the veins in the white, the wet sheen of the cornea) is generated procedurally, without a single photograph. It's fully adjustable and rigged to animate, pupil dilation included.

It is one of my commercial products, available on Superhive (Blender Market). A portion of the proceeds from all my products goes to the Blender Foundation Development Fund, supporting the software they are built with.

[Buy on Superhive|website](https://superhivemarket.com/creators/tomoco)

---

## My Role

Designed, built, and rigged entirely by me in **Blender**, with controls over vein density, iris and sclera colour, and more.

![Eye variation](3d-assets/eye_details/var3.png)
![Eye variation](3d-assets/eye_details/var4.png)
![Eye variation](3d-assets/eye_details/var5.png)

---

## Why I Made It

I built it for my own work, a reusable and fully parametric eye I can drop into any character and tune to fit rather than rebuilding eyes from scratch. It's used in my piece *Ardo*, in the **3D Art** section. Once it was that reusable, it became something worth packaging and selling too.

![The full range of eyes the setup can generate](3d-assets/eye_details/allVars.png)
*Every iris, colour, and vein pattern is procedurally generated*
`,
    },
    {
      id: 'fabric', src: '3d-assets/fabricThumb.png', alt: 'Procedural fabric weave material', cols: 4, rows: 2,
      title: 'Procedural Fabric Material',
      description: 'A reusable fabric material I built in Blender that can become almost any woven cloth.',
      page: `
## About

![A close-up of the woven fabric material](3d-assets/fabric_details/detail1-min.png){right}

One material that spans a huge range of woven cloth: a few controls take it from a broad basket-weave to a tight cloth knit, and it stays physically believable throughout.

It is one of my commercial products, available on Superhive (Blender Market). A portion of the proceeds from all my products goes to the Blender Foundation Development Fund, supporting the software they are built with.

[Buy on Superhive|website](https://superhivemarket.com/creators/tomoco)

---

## My Role

Designed and built entirely by me in **Blender**, driven by a single node group that exposes the weave pattern, scale, colour, and wear.

![Fabric weave variation](3d-assets/fabric_details/detail2-min.png)
![Fabric weave variation](3d-assets/fabric_details/detail4-min.png)

---

## Why I Made It

I built it for my own personal and commercial projects as a single fully parametric tool, so any woven fabric can be dialled in instead of being modelled or textured from scratch each time. It's used in some of those projects, such as *Another Day at the Office*. That same generality is what let me turn it into one of my products.

![A final fabric weave variation](3d-assets/fabric_details/detail5-min.png){left}

A single node group exposes the weave pattern, scale, colour, and wear, so the same material covers everything from coarse upholstery to fine garment cloth.
`,
    },
    {
      id: 'paint', src: '3d-assets/paintThumb.png', alt: 'Procedural brushstroke painting material', cols: 4, rows: 2,
      title: 'Brushstroke Painting Material',
      description: 'A Blender shader I built that turns any image into an oil painting of broad brushstrokes on canvas.',
      page: `
## About

Feed it any image and it re-renders the picture as if painted onto canvas with broad strokes, with the paint visibly thicker where the source is brighter.

![Broad brushstrokes on canvas](3d-assets/paint_details/im2.png)
![Another image through the painting shader](3d-assets/paint_details/im5.png)
*The same shader applied to two different source images: impasto thickness follows each one's brightness*

It is one of my commercial products, available on Superhive (Blender Market). A portion of the proceeds from all my products goes to the Blender Foundation Development Fund, supporting the software they are built with.

[Buy on Superhive|website](https://superhivemarket.com/creators/tomoco)

---

## My Role

Built entirely by me in **Blender**, with the brushstroke thickness (the impasto) driven procedurally by the brightness of the source image.

---

## Why I Made It

I built it for my own personal and commercial projects, a reusable shader that turns any image into something reading as a real, physical painting automatically. It started as a study in that effect, and once it was general enough to reuse, it also became a product, not just a study.
`,
    },
  ],
  '3D Art': [
    {
      id: 'alt-realities', src: '3d-art/thumb1.mp4', alt: 'Forest clearing with a worker and floating debris', cols: 4, rows: 2,
      title: 'Another Day at the Office',
      description: 'An early 3D scene I made in Blender for a 2021 community art challenge, with everything but the character\'s walk built by me.',
      page: `
## About the Piece

A short scene made for Pwnisher's *Alternate Realities* challenge (2021): a plague doctor in a forest clearing, dragging another body to add to the pile. Contestants were given the motion-capture animation and the general composition: every entry had to work a circle into the upper-right corner of the frame. Here it reads as **negative space** rather than a literal object.

---

## My Role

I made everything but the character's walk animation and camera settings, built and rendered entirely in **Blender**:

- **Modelling, texturing, and lighting** of the full environment, characters, and objects
- **Scattered detail**: the forest trees and the grass field
- **Cloth simulation** for the clothing and the tarp
- **A swarm of flies** driven by a flocking (boid) simulation
- **Scene lighting and post-processing**, including multi-layered renders, compositing of additional elements like the lens flare, etc.

---

## Why I Made It

It's one of my early pieces, and much of what I learned about building a full scene start to finish (environment, simulations, lighting) came out of making it. I used many of these kinds of challenges to grow as an artist.
`,
    },
    {
      id: 'ardo', src: '3d-art/thumb2.png', alt: 'Character screaming as he burns in a nighttime wildfire', cols: 2, rows: 2, title: 'Ardo.',
      description: 'A personal 3D piece I made entirely in Blender, picturing a man burning alive in a night-time fire.',
      page: `
## About the Piece

*Ardo.* (2024) means *I burn* in Spanish, and the image takes the title at its word: a man burns alive in a forest fire at night, the frame held close on his head as he screams. What carries it is the contrast between the figure and the night around him: the fire violent and immediate, the dark forest sky behind it still and completely indifferent.

---

## My Role

Built end-to-end on my own in **Blender**, including two of my own custom assets (both in the **3D Tech** section).

I sculpted the head from scratch. The screaming expression took most of the passes. A face that extreme slips into caricature very easily, and it had to stay believable for the image to land. Another important focus was on the lighting and post-processing: fire wants to dominate every frame it's in, and I wanted the stillness of the night to survive beside it, so the intensity of the flames and the calm of the dark could share one frame without either flattening the other. I created some of my procedural assets for this piece, including the material for the burning flesh and the parametric assets for the eyes.

![Procedural Flesh material](3d-assets/flesh_details/var1_comp.png){right}
*Flesh: a fully parametric skin-and-tissue material.*

The skin is driven by my **Flesh** material, raw, living tissue with warmth, wetness, and pore-level detail, all built procedurally rather than from photographs.

![Procedural Eyes](3d-assets/eye_details/var2.png){left}
*Eyes: anatomically detailed and rigged.*

The **Eyes** are anatomically detailed and rigged, their pattern and detail generated without a single image texture.

---

## Why I Made It

I made it during a period of intense rage and despair, with one intent: to give that state a body, so it could exist somewhere outside of me. There's no story around it and no second meaning intended. It's what that period felt like from the inside, made as direct as the feeling was. Rage is loud, but despair is the part where the world around you doesn't react; by the time it was finished, the feeling had somewhere to live that wasn't me.
`,
    },
    {
      id: 'menpo', src: '3d-art/thumb3.jpeg', alt: 'Sculpted Japanese menpō face armour', cols: 2, rows: 4, title: 'Menpō (面頬)',
      description: 'A 3D modelling study I made end-to-end in Blender of a Japanese menpō, the half-face armour worn beneath a samurai helmet.',
      page: `
## About the Piece

A *menpō* (2021) is the half-face armour samurai wore beneath the helmet. This study recreates one covered in lacquered leather, with the focus on the facial anatomy underneath the mask. It was one of my first attempts at sculpting a face.

---

## My Role

Modelled, shaded, lit, and composed entirely by me in **Blender**. The work focused on three things:

- **Facial anatomy**: getting the underlying structure right so the mask reads as a face, not just a shape
- **Hard-surface shading**: worn, hammered metal with believable wear and highlights
- **Composition**: framing and lighting that give the piece presence

---

## Why I Made It

The draw was the face itself: studying its anatomy and translating it into hard, forged metal. It's a study, made to get better at both halves of that problem.
`,
    },
    {
      id: 'ciudad-faro', src: '3d-art/ciudadFaroThumb.png', alt: 'Lighthouse surrounded by floating whales', cols: 2, rows: 2, title: 'Ciudad Faro',
      description: 'A 3D piece I made end-to-end in Blender, rebuilding the cover painting of Burning Caravan\'s album *Ciudad Faro* as a three-dimensional scene.',
      page: `
## About the Piece

*Ciudad Faro* (2022) rebuilds the album cover of the same name by **Burning Caravan**, a Colombian band I love, as a dimensional scene: floating whales and their skeletons drifting around a lighthouse, lit volumetrically to echo the mood of the original painting.

---

## My Role

Built start to finish on my own in **Blender**:

- **The whales and their skeletons**, the central forms, modelled from scratch
- **The lighthouse** that anchors the composition
- **Volumetric lighting** to carry the mood and depth of the original painting

---

## Why I Made It

It's a tribute to Burning Caravan, whose music I love, and an exercise in translating a flat painting into a scene with real depth and light, taking something I admired and rebuilding it in my own medium.
`,
    },
    {
      id: 'brain-farm', src: '3d-art/marsThumb.png', alt: 'Fantastical greenhouse on Mars powering a brain', cols: 4, rows: 2, title: 'Brain Farm',
      description: 'A 3D piece I made end-to-end in Blender, picturing a fantastical greenhouse on Mars that powers a giant brain.',
      // Optional `page` Markdown drives the detail-view body (parsed by parseMarkdown).
      // Same syntax as a GAMES item's `page`: ## headings, paragraphs, --- dividers,
      // - lists, ![alt](path) images (path relative to src/assets/thumbnails/), and
      // [Label|icon](url) link rows. When omitted, the short `description` is shown instead.
      page: `
## About the Piece

A surreal scene: a fantastical greenhouse on Mars powering a giant brain. It belongs to an ongoing series of mine built around brains and strange worlds that frame them.

![Brain-City companion study](3d-art/brainCityThumb.png){right}
*Brain-City, a companion study: a vast city floating in space, powered by a brain (or is it a brain powered by a city?).*

The companion **Brain-City** piece extends the same idea into a sprawling city suspended in space.

---

## My Role

A stylised composite built and rendered start to finish by me in **Blender**:

- **Modelling and shading** the brain, structures, and character
- **Particle systems** scattering the rocks across the Martian surface
- **Volumetric atmosphere** graded in post

---

## Why I Made It

It's part of an ongoing personal exploration of brain-themed surrealism, a motif I keep returning to and reframing in different worlds.
`,
    },
    {
      id: 'ascension', src: '3d-art/ascensionThumb.png', alt: 'Abstract volumetric light and particles', cols: 2, rows: 2, title: 'Ascension V',
      description: 'An abstract 3D piece I made end-to-end in Blender, drawn from *Ascension* by the artist Moebius.',
      page: `
## About the Piece

*Ascension V* (2025) is an abstract study drawn from **Moebius'** work *Ascension*: glowing volumetric light and drifting humans shaping forms in space.

---

## My Role

Made entirely by me in **Blender**, focused on two things:

- **Volumetric lighting** as the main subject: light you can see moving through the space
- **Particle simulation** scattering human shapes to form patterns

---

## Why I Made It

Moebius is a long-standing influence on my work, and this is an abstract study made in his direction, a way of learning from an artist I admire by working in his register. I found this piece particularly evocative and wanted to try to find the same sensation in my own style.
`,
    },
    {
      // hasAudio: the clip has a soundtrack — detail/doc views attach custom
      // video controls (play/pause/seek/mute) so visitors can unmute it.
      id: 'frenesi', src: '3d-art/Frenesi.webm', alt: 'Animated short film still', cols: 2, rows: 2, title: 'Frenesí', hasAudio: true,
      kindLabel: 'FILM', // deck-card chip — it's an awarded short film, not a "3D" still

      description: '*Frenesí* (2022) is a short animated film I directed, produced, and made entirely on my own (aside from voice acting), about drug use, gender, and sexuality in Colombia.',
      page: `
## About the Piece

A short animated film about psychoactive-substance use and its ties to gender and sexuality, important subjects in Colombia, with taboos that have cost many lives.  

The film won 2nd place in the animation category at the 8th *Festival de Cortos Psicoactivos* (Psychoactive Short Film Festival) in Bogotá.

---

## My Role

I directed and produced the film, and apart from the voice acting, made the whole thing myself in **Blender (Cycles)**: modelling, animation, shading, lighting, rendering, and sound design.

---

## Why I Made It

I grew up in a society where drug use, sex, and gender identity are wrapped in taboo, and in Colombia the cost of that taboo is not abstract. It is violence. The drug trade has fed decades of armed conflict, yet the stigma often lands hardest on the people who use: discriminated against, pushed to the margins, and in the worst cases attacked in so-called social cleansing. Trans and queer Colombians are harassed and killed for being visible. None of this is prevented by the silence around these subjects. The silence is what lets it continue.

Taboo also does its quieter damage. When something can't be discussed openly, people can't ask questions or get accurate information, and seeking help comes with shame attached. Stigma doesn't stop drug use and it doesn't make anyone's identity disappear. It pushes both into the dark, where the harm compounds.

Breaking a taboo is not the same as promoting what it hides. People are going to use substances, have sex, and live across the spectrum of gender whether we talk about it or not. Talking about it honestly is what makes those realities safer and the people living them less alone. That principle is at the core of harm reduction, and it is the reason this film exists.

*Frenesí* treats these subjects as ordinary parts of human experience. In a country where saying that out loud is still difficult, that **was worth making**.

---

## Recognition

**2nd place, Animation category** at the 8th *Festival de Cortos Psicoactivos* (Psychoactive Short Film Festival), out of hundreds of submissions. The festival is run by **Échele Cabeza**, a Colombian harm-reduction NGO.
`,
    },
    {
      id: 'bioshock', src: '3d-art/bioshockThumb.webm', alt: 'Recreated BioShock hallway', cols: 2, rows: 2, title: 'Bioshock Hallway',
      description: 'A 3D recreation of a corridor from the video game *BioShock*, built end-to-end in Blender.',
      page: `
## About the Piece

A recreation of a corridor from the original *BioShock* (2023), a study in modelling, materials, and composition that captures the game's period look and claustrophobic mood.

---

## My Role

Built end-to-end in **Blender**:

- Every asset modelled, textured, and shaded by me, except for the vending-machine texture image.
- Period materials: worn brass, mouldy wallpaper, water-stained surfaces
- Lighting and framing tuned to the game's claustrophobic mood

---

## Why I Made It

*BioShock* is a game I love, and its art direction is some of the most distinctive I know. I wanted to explore it firsthand, to understand how that world is built by rebuilding a piece of it myself.
`,
    },
    {
      id: 'rebel-chase', src: '3d-art/starWarsChaseThumb.webm', alt: 'X-Wing chasing a TIE Fighter', cols: 2, rows: 2, title: 'Rebel Dogfight',
      description: 'A Star Wars-inspired 3D scene I made in Blender, of an X-Wing chasing down a TIE Fighter.',
      page: `
## About the Piece

A short cinematic shot in the Star Wars vein: an **X-Wing** running down a **TIE Fighter** through space, built around a fast, readable action-camera chase and an explosion finish.

---

## My Role

Made in **Blender** in 2022. The X-Wing model was sourced online; everything else is mine:

- **Action-camera animation**: choreographing a fast, readable dogfight
- **Environment design** for the surrounding space
- **TIE Fighter modelling**
- **Explosion VFX**, simulated using Blender's built-in fluid dynamics.

---

## Why I Made It

I wanted to push myself on motion, framing, and timing. Animating a fast, readable dogfight is a different problem from a still image, and this was the piece where I went after it.
`,
    },
  ],
};
